config/routes.rb
Readit::Application.routes.draw do
  get "comments/show"

  get "links/new"

  devise_for :users

  resources :pages
  resources :links do
    resources :comments
  end

  

  root :to => 'pages#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :message, :link_id

  belongs_to  :user
  belongs_to  :link

  def username
    if self.user
      self.user.email
    else
      "anonymous"
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :title, :url

  belongs_to :user

  def username
    if self.user
      self.user.email
    else
      "anonymous"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :username, :email

  has_many  :links
  has_many  :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_filter :redirect_back_unless_logged_in
  
  def create
    @comment = current_user.comments.create(params[:comment].merge(link_id: params[:link_id]))
    redirect_to :back
  end

  def redirect_back_unless_logged_in
    redirect_to :back, alert: "You need to log in." unless current_user.present?
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def new
    @link = Link.new
  end

  def edit
    @link = Link.find_by_id(params[:id])
  end

  def create
    @link = current_user.links.build(params[:link])
    
    if @link.save
      redirect_to @link
    else
      render action: 'new'
    end
  end

  def show
    @link = Link.find_by_id(params[:id])
    @comment = @link.comments.build
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index

    params[:page]     ||= 1
    params[:per_page] ||= 10

    @links = Link.order('created_at DESC').page(params[:page].to_i).per_page(params[:per_page].to_i)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Readit</title>
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <script type="text/javascript" src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="brand" href="/">ReadIt</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <% if current_user.present? %>
              <li class="active"><%= link_to "<i class='icon-plus'></i>".html_safe, new_link_path %></li>
              <!-- <li class="active"><%= link_to ' + ', new_link_path %></li> -->
              <li class="offset1"><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to 'Log in', new_user_session_path %></li>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
  
  <div class="container">
    <% if !notice.nil? %>
      <p class="alert alert-info notice"><%= notice %></p>
    <% end %>
    <% if !alert.nil? %>
      <p class="alert"><%= alert %><button type="button" class="close" data-dismiss="alert">&times;</button></p>
    <% end %>

    <%= yield %>
    
  </div>

</body>
</html>

app/views/links/edit.html.haml
edit.html.haml

app/views/links/new.html.haml
= form_for @link, html: { :class => "form-signin"} do |f|
  - if @link.errors.any?
    #error_explanation
      %h2= pluralize(@link.errors.count, "error") + "prohibited this link from being saved:"
      %ul
        - @link.errors.full_messages.each do |msg|
          %li= msg
          
  %h2.form-signin-heading Submit a new link
  = f.text_field :title, :autofocus => true, :class => "input-xxlarge", :placeholder => "Title"
  %br
  = f.text_field :url, :class => "input-xxlarge", :placeholder => "URL"
  %br
  = f.submit "Submit", :class => "btn btn-large btn-primary"
  = link_to "Cancel", pages_path, :class => "btn"

app/views/links/show.html.haml
%h2= link_to @link.title, @link.url, target: "_blank"
%p.muted
  %i.icon-user
  = " " + @link.username
  %i.icon-calendar
  = " " + @link.created_at.strftime('%b %d, %Y at %I:%M:%S %p')

/ Display previous comments
%h3.form-signin-heading Comments
- @link.comments.each do |comment|
  - if !comment.message.nil?
    %p.muted
      %i.icon-user
      = " " + comment.username
      %i.icon-calendar
      = " " + comment.created_at.strftime('%b %d, %Y at %I:%M:%S %p')
    %blockquote
      - comment.message.split(/\r?\n/).each do |comment_line|
        %p= comment_line


/ Display the text area for a new comment
= form_for [@link, @comment], html: { :class => "form-signin"} do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= pluralize(@comment.errors.count, "error") + "prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg
          
  = f.text_area :message, :autofocus => true, :placeholder => "Comment here...", :class => "comment-text"
  %br
  = f.submit "Submit", :class => "btn"

app/views/pages/index.html.haml
-if !current_user.present?
  .alert
    %button.close{type: "button", :'data-dismiss' => "alert"} &times;
    Please log in to post new links or sign up if you haven't created an account yet

%ul.unstyled
  - @links.each do |link|
    %li.lead
      = link_to link.title, link.url, target: "_blank"
      / = link_to "<i class='icon-comment'> </i>".html_safe, link
      = link_to "<span class='badge'>#{link.comments.count}</span>".html_safe, link

%br
.page_info
  = page_entries_info @links
= will_paginate @links, renderer: BootstrapPagination::Rails